--회원정보테이블
CREATE TABLE MOVIE_MEMBER (
    ID VARCHAR2(20) PRIMARY KEY,
    PASSWORD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(300) NOT NULL,
    PAY NUMBER(30) NOT NULL,
    POINT  NUMBER(30)
);

--영화정보테이블
CREATE TABLE MOVIES (
    TIME VARCHAR2(20) NOT NULL,
    JENRE VARCHAR2(300) NOT NULL,
    MOVIE VARCHAR2(300) NOT NULL, --영화제목
    GRADE VARCHAR2(20) NOT NULL, --별점
    ACTOR VARCHAR2(30) NOT NULL
);
--예매테이블
CREATE TABLE MOVIE_RESERVE (
    NAME VARCHAR2(30) NOT NULL,
    MOVIE VARCHAR2(300) NOT NULL,
    PRICE  NUMBER(30) NOT NULL,
    MEMBER_NUMBER VARCHAR2(20) NOT NULL,  --예매인원
    MOVIE_DATE DATE NOT NULL, --날짜
    TIME VARCHAR2(20) NOT NULL,
    SEAT VARCHAR2(300) PRIMARY KEY
);