-- 테이블 삭제
-- DROP TABLE QNABOARD;
-- DROP TABLE ORDERS;
-- DROP TABLE NOTICEBOARD;
-- DROP TABLE CART;
-- DROP TABLE BOOK_REVIEW;
-- DROP TABLE BOOK;
-- DROP TABLE CATEGORY;
-- DROP TABLE MEMBERS;

-- 테이블 생성
CREATE TABLE MEMBERS (
   MEM_ID VARCHAR2(40) PRIMARY KEY,
   MEMPW VARCHAR2(20) NOT NULL,
   NAME VARCHAR2(20) NOT NULL,
   ADDRESS VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(20) NOT NULL,
   BIRTH VARCHAR2(8) NOT NULL,
   EMAIL VARCHAR2(50)
);

CREATE TABLE QNABOARD (
   Q_BOARD_ID NUMBER PRIMARY KEY, -- 시퀀스 노캐시 적용
   MEM_ID VARCHAR2(40) NOT NULL,
   Q_MEM_ID VARCHAR2(20) NOT NULL, -- 뒤 4자리 * 표시
   TITLE VARCHAR2(40) NOT NULL,
   CONTENTS VARCHAR2(1000) NOT NULL,
   BOARDPW NUMBER NOT NULL, -- 작성 전 비밀번호 설정
   ANSWER VARCHAR2(40) NOT NULL, -- DEFAULT 미완료   , 완료시 -> 답변완료
   CREATEDAT DATE NOT NULL, -- DEFAULT SYSDATE
   IMAGE VARCHAR2(40) NULL,
   SECRET NUMBER NULL, -- 0, 1 > 비밀글 공개글

   CONSTRAINT QNABOARD_MEM_ID_FK FOREIGN KEY (MEM_ID) REFERENCES MEMBERS(MEM_ID) ON DELETE CASCADE -- 외래키 설정
);

CREATE TABLE NOTICEBOARD (
   N_BOARD_ID NUMBER NOT NULL,
   TYPE VARCHAR2(40) NOT NULL, -- 이벤트, 배송 관련 등
   TITLE VARCHAR2(40) NOT NULL,
   CREATEDAT DATE NOT NULL
);

CREATE TABLE CATEGORY (
    CATEGORY VARCHAR2(30) PRIMARY KEY
);

CREATE TABLE "BOOK" (
   BOOK_ID NUMBER(3) PRIMARY KEY,
   BOOKNAME VARCHAR2(100) NOT NULL,
   PRICE NUMBER(5) NOT NULL,
   PUBLISHER VARCHAR2(50) NOT NULL,
   PUB_DATE DATE NOT NULL,
   AUTHOR VARCHAR2(50) NOT NULL,
   GRADE_AVG NUMBER(2, 1) NULL,
   BOOK_CNT NUMBER(3) NULL,
   ORDER_CNT NUMBER(5) NULL,
   DETAILS   VARCHAR2(300) NULL,
   BOOK_IMAGE   VARCHAR2(300) NULL,
   CATEGORY VARCHAR2(30) REFERENCES CATEGORY (CATEGORY)
);

CREATE TABLE "BOOK_REVIEW" (
   "REVIEW_ID"   NUMBER(3) PRIMARY KEY,
   "REVIEW_CONTENT" VARCHAR(300) NOT NULL,
   "GRADE"   NUMBER(2,1) NULL,
   "BOOK_ID" NUMBER(3),  
   "MEMBER_ID"   VARCHAR2(20) NOT NULL
);

ALTER TABLE "BOOK_REVIEW"       --BOOK_REVIEW 테이블의 BOOK_ID제약조건추가 코드
ADD CONSTRAINT FK_BOOK_REVIEW_BOOK
FOREIGN KEY ("BOOK_ID")
REFERENCES "BOOK" ("BOOK_ID");

ALTER TABLE "BOOK_REVIEW"       --BOOK_REVIEW 테이블의 MEMBER_ID제약조건추가 코드
ADD CONSTRAINT FK_BOOK_REVIEW_MEMBER
FOREIGN KEY ("MEMBER_ID")
REFERENCES "MEMBERS" ("MEM_ID");

CREATE TABLE "ORDERS" (
   "ORDER_ID"   VARCHAR2(20)   PRIMARY KEY,
   "SUM_PRICE"   NUMBER(10)      NOT NULL,
   "DLVYDATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "DLVYPRICE"   DATE   DEFAULT SYSDATE+3   NOT NULL,
   "BOOK_ID"   NUMBER(3)      NOT NULL,
   "MEM_ID"   VARCHAR2(20)   NOT NULL,
   "PAYMENT"   VARCHAR(20)      NULL,
   "POINT"   NUMBER(10)      NULL,
   "CANCEL"   CHAR      NULL
);

CREATE TABLE "CART" (
   "BOOK_CNT"   NUMBER(3)      NULL,
   "BOOK_ID"   NUMBER(5)      NOT NULL,
   "MEM_ID"   VARCHAR2(20)   NOT NULL,
   "SUM_PRICE"   NUMBER(10)      NOT NULL
);

ALTER TABLE "ORDERS" 
    ADD CONSTRAINT FK_ORDERS_MEMBER 
    FOREIGN KEY ("MEM_ID") 
    REFERENCES "MEMBERS" ("MEM_ID");
    
ALTER TABLE "ORDERS" 
    ADD CONSTRAINT FK_ORDERS_BOOK 
    FOREIGN KEY ("BOOK_ID") 
    REFERENCES "BOOK" ("BOOK_ID");

ALTER TABLE "CART" 
    ADD CONSTRAINT FK_CART_MEMBER 
    FOREIGN KEY ("MEM_ID") 
    REFERENCES "MEMBERS" ("MEM_ID");
    
ALTER TABLE "CART" 
    ADD CONSTRAINT FK_CART_BOOK 
    FOREIGN KEY ("BOOK_ID") 
    REFERENCES "BOOK" ("BOOK_ID");

-- 시퀀스 추가
CREATE SEQUENCE QNABOARD_SEQ NOCACHE;
CREATE SEQUENCE NOTICEBOARD_SEQ NOCACHE;


--BOOK테이블 변경
CREATE SEQUENCE BOOKID_SEQ NOCACHE;
ALTER TABLE BOOK MODIFY GRADE_AVG NUMBER;
CREATE SEQUENCE REVIEW_ID_SEQ NOCACHE;
ALTER TABLE BOOK
ADD REVIEW_ID NUMBER(3) REFERENCES BOOK_REVIEW (REVIEW_ID);

ALTER TABLE BOOK_REVIEW
ADD REGDATE DATE;

ALTER TABLE BOOK
DROP COLUMN GRADE_AVG;


--CART테이블 변경
ALTER TABLE CART 
ADD (BOOKNAME VARCHAR2(100) NOT NULL);

ALTER TABLE CART RENAME COLUMN SUM_PRICE TO PRICE;
-------------------------------
ALTER TABLE BOOK MODIFY GRADE_AVG NUMBER;
2000	출판사2	23/09/05	저자1	3.5	100	50	111	스크린샷 2023-09-16 160646.png	소설	
2000	출판사2	23/09/29	저자1	3.5	100	33	111	스크린샷 2023-06-21 185724.png	인문과학	
3000	출판사2	23/09/20	저자1	3.5	100	80	111	스크린샷 2023-07-23 135339.png	경제경영	
1000	출판사	23/10/02	저자1	3.5	100	10	111	스크린샷 2023-10-02 133118.png	어린이	
1000	출판사	23/10/25	저자1	3.5	100	30	111	스크린샷 2023-07-23 135326.png	소설	